name: Deploy to Koyeb

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Install Koyeb CLI
        uses: koyeb-community/koyeb-actions@v2
        with:
          api_token: ${{ secrets.KOYEB_API_TOKEN }}
      
      - name: Trigger Koyeb Redeploy
        run: koyeb service redeploy eshop/eshop-service
