name: Deploy to Koyeb

on:
  push:
    branches:
      - main
      - module-2-exercise

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Install and setup Koyeb CLI
        uses: koyeb/action-setup-koyeb@v1
        with:
          api-token: ${{ secrets.KOYEB_API_TOKEN }}
      
      - name: Trigger Koyeb Redeploy
        run: koyeb service redeploy eshop/eshop-service
